{% set name = "datacompy" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95fafc1f46b2697cac2c2b4fcf3736ba60301e7c2528e2e90a23f9f33d6afa19

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ordered-set >=4.0.2
    - numpy >=1.11.3
    - pandas >=0.25.0
    - python >=3.6


test:
  imports:
    - datacompy

about:
  home: https://github.com/capitalone/datacompy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pandas and Spark DataFrame comparison for humans

extra:
  recipe-maintainers:
    - pg-hbk
    - sy-hbk
    - fdosani
    - elzzhu
    - jborchma
