travis:
  secure:
    BINSTAR_TOKEN: gCGvxlV/4sLGeQ3G5jumZzxMiR7fkMA1oZQbQE59MewlwMwSnI0ebHnuxLPnwYamyPAyg5O7yRaLHt2QE15PHwg5Hkn10AQnhmZJimkvQFXxG1JrUqTFztoCVDP12YgyDPROIlwjPn1nLZpNku9GkMmb7GiqTPWaIH9IIitWoV+MvJwfqkNWNFZzk8FauUXVogUVIyZKyDgZw552nGOnPQ/Ouqe4Z8+R5R44ld1s5XoZjj5ITHMkawKRoPJ2f6KB83Se/Rp/6BxrorLGXaPrSLeqsNDN8JIgH+mbKHx5fGyPm4taYKEKp09i7EYZskYumY6SE462hzR17ii6KUrOe8/rDjW0fRS6Ps5/ZFHODxHTO3Bsn7AuB0UU/KaNBYXnA1HTFTxpLIJ65GwwWau3WozAZt9vsjWyKGHKbsWAxdoTr+5uBexqgwo6SPajWeO0JmnIIs2ppP7AQh9eujABs+o5gqew0mkKTumaLrFA35O3GnXtmgAZk0pbMfF8s12yWY9Km8UU/TiSCF9H3SCSztCCjYAZUqJmzJV1Z5OmuvbD9TFYsSe5iFlv03PjVlLemLcOgj2G3f5upNFuSgLeoVFOsXblkkEYqWdXwt0zcIBOrdBBuLp0Ac8BQDNeBnogC9dkh4hi1LBjpt/s9/sUWdg8b8o7tMJU6Jt+tFXKgeU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
